Lab1/WEB_953505_MANKEVICH/WEB_953505_MANKEVICH/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WEB_953505_MANKEVICH.Extensions;
using WEB_953505_MANKEVICH.Models;

namespace WEB_953505_MANKEVICH.Components
{
    public class CartViewComponent : ViewComponent
    {
        private Cart _cart;

        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            var cart = HttpContext.Session.Get<Cart>("cart");
            return View(cart);
        }
    }
}

Lab1/WEB_953505_MANKEVICH/WEB_953505_MANKEVICH/Components/MenuViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using WEB_953505_MANKEVICH.Models;

namespace WEB_953505_MANKEVICH.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly List<MenuItem> _menuItems = new()
        {
            new() {Controller = "Home", Action = "Index", Text = "Lab 2"},
            new() {Controller = "Product", Action = "Index", Text = "Каталог"},
            new() {IsPage = true, Area = "Admin", Page = "/Index", Text = "Администрирование"}
        };

        public IViewComponentResult Invoke()
        {
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];

            foreach (var item in _menuItems)
            {
                var matchController = controller?.Equals(item.Controller) ?? false;
                var matchArea = area?.Equals(item.Area) ?? false;

                if (matchController || matchArea) item.Active = "active";
            }

            return View(_menuItems);
        }
    }
}

Lab1/WEB_953505_MANKEVICH/WEB_953505_MANKEVICH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.15.3-web/css/all.css">
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">WebLabsV06</a>
        <div class="navbar-nav">
            @await Component.InvokeAsync("Menu")
        </div>
        <partial name="_UserPartial"/>
    </nav>
</header>
<div class="col-md-10 offset-1">@RenderBody()</div>
<footer>
    <div class="navbar navbar-dark navbar-expand-md bg-dark">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="https://www.facebook.com">
                <i class="fab fa-facebook-f fa-2x"></i>
            </a>
            <a class="nav-item nav-link" href="https://www.vk.com">
                <i class="fab fa-vk fa-2x"></i>
            </a>
            <a class="nav-item nav-link" href="https://www.twitter.com">
                <i class="fab fa-twitter fa-2x"></i>
            </a>
        </div>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

Lab1/WEB_953505_MANKEVICH/WEB_953505_MANKEVICH/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> _signInManager;


@if (_signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")

    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light"/>
        </div>

        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <li class="dropdown-item-text">
                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="30" alt="User"
                     class="rounded bg-light"/>
                @if (User.Identity != null)
                {
                    @User.Identity.Name
                }
            </li>
            <li class="dropdown-divider"></li>
            <form class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout"
                  asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit" value="Log off"/>
            </form>
        </ul>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>
}